# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usuari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='favorit',
            name='postFavorit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='favorit',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.Perfil'),
        ),
    ]
