# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-21 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180509_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorit',
            name='data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 5, 21, 14, 5, 2, 180877, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
