# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votsNegatius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='votsPositius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
